In [1]:
%load_ext autoreload
%autoreload 2
import sys; sys.path.append("../src")
import pandas as pd
from search import search

pd.set_option("display.max_colwidth", None)

c:\GitHub\stockholm-job-rag\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 6686.32it/s]

In [2]:
search("data analyst SQL Python")[["title", "score"]]

                                 title     score
465                       Data Analyst  0.657580
80   Data Analyst – Data Visualization  0.539456
464                       Data Analyst  0.534366
315                      Data Engineer  0.530315
328                     Data Scientist  0.527138

In [3]:
search("data analyst R svenska")[["title", "score"]]

                                                  title     score
416                                 Junior Data Analyst  0.646838
437             Dataanalytiker till Svenska Röda Korset  0.642997
112                                        Data Analyst  0.639319
443  Strategisk Dataanalytiker till Svenska Röda Korset  0.635360
107                          Data Engineer with Swedish  0.629124

In [4]:
search("AI Engineer python RAG")[["title", "score"]]

,title,score
154,Hands-on AI Engineer,0.590313
5,AI Engineer (Agentic AI / Full-Stack): Founding Engineer at a Stealth AI lab,0.562545
247,AI Engineer,0.555095
85,AI Engineer,0.545598
242,Software & AI Engineering Consultant (C# / .NET),0.543022

In [5]:
search("AI Engineer R, Java, .Net")[["title", "score"]]

,title,score
242,Software & AI Engineering Consultant (C# / .NET),0.667719
491,Front End AI Engineer,0.663967
342,AI Engineer,0.661114
250,Software & AI Engineering Program (C# / .NET),0.653477
5,AI Engineer (Agentic AI / Full-Stack): Founding Engineer at a Stealth AI lab,0.648994